title: App Dashboard
subtitle: Home Server
documentTitle: Home
icon: fas fa-home

header: true
footer: false

columns: "3"
connectivityCheck: false

theme: default

links:
  - name: GitHub
    icon: fab fa-github
    url: https://github.com/mchill/home

services:
  - name: Media
    icon: fas fa-compact-disc
    items:
      - name: Plex
        subtitle: Videos
        logo: assets/logos/plex.png
        url: https://plex.mchill.io
      - name: Audiobookshelf
        subtitle: Audiobooks
        logo: assets/logos/audiobookshelf.png
        url: https://books.mchill.io
      - name: File Browser
        subtitle: Files
        logo: assets/logos/filebrowser.png
        url: https://files.mchill.io

  - name: Libraries
    icon: fas fa-folder-open
    items:
      - name: Radarr
        subtitle: Movies
        logo: assets/logos/radarr.png
        url: https://radarr.mchill.io
      - name: Sonarr
        subtitle: TV shows
        logo: assets/logos/sonarr.png
        url: https://sonarr.mchill.io
      - name: Readarr
        subtitle: Books
        logo: assets/logos/readarr.png
        url: https://readarr.mchill.io
      - name: Bazarr
        subtitle: Subtitles
        logo: assets/logos/bazarr.png
        url: https://bazarr.mchill.io

  - name: Media Mgmt
    icon: fas fa-tasks
    items:
      - name: Overseerr
        subtitle: Plex requests
        logo: assets/logos/overseerr.png
        url: https://overseerr.mchill.io
      - name: Tdarr
        subtitle: Transcoder
        logo: assets/logos/tdarr.png
        url: https://tdarr.mchill.io
      - name: Transmission
        subtitle: BitTorrent client
        logo: assets/logos/transmission.png
        url: https://transmission.mchill.io
      - name: Jackett
        subtitle: Indexer aggregator
        logo: assets/logos/jackett.png
        url: https://jackett.mchill.io

  - name: Server Mgmt
    icon: fas fa-server
    items:
      - name: K8s Dashboard
        subtitle: Cluster configuration
        logo: assets/logos/kubernetes.png
        url: https://k8s.mchill.io
      - name: Traefik
        subtitle: Proxy configuration
        logo: assets/logos/traefik.png
        url: https://traefik.mchill.io
      - name: Synology DSM
        subtitle: NAS web UI
        logo: assets/logos/nas.png
        url: https://nas.mchill.io
      - name: Router
        subtitle: Router web UI
        logo: assets/logos/router.png
        url: https://router.mchill.io

  - name: Monitoring
    icon: fas fa-heartbeat
    items:
      - name: Tautulli
        subtitle: Plex statistics
        logo: assets/logos/tautulli.png
        url: https://tautulli.mchill.io
      - name: Grafana
        subtitle: Server monitoring
        logo: assets/logos/grafana.png
        url: https://grafana.mchill.io
      - name: Prometheus
        subtitle: Server metrics
        logo: assets/logos/prometheus.png
        url: https://prometheus.mchill.io
      - name: DDNS Monitor
        subtitle: Domain management
        logo: assets/logos/ddns.svg
        url: https://ddns.mchill.io

  - name: More
    icon: fas fa-plus
    items:
      - name: Home Assistant
        subtitle: Home automation
        logo: assets/logos/homeassistant.png
        url: https://home.mchill.io
      - name: Pi-hole
        subtitle: DNS sinkhole
        logo: assets/logos/pihole.png
        url: https://pihole.mchill.io
      - name: Jitsi
        subtitle: Video conferencing
        logo: assets/logos/jitsi.png
        url: https://jitsi.mchill.io
