---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ceph-csi-rbd-secret
  namespace: ceph-csi-rbd
spec:
  encryptedData:
    userID: AgAu+m2Ym8Po/8oE4cfDhfbgpLVsITBauRYKLFT97GDzfomvTa8NpWjVrLKjezDzfBLJusnuQjfy21F5/TTkboLW9+g6ZEzxVrZQsYjkvO5fYm8UEPrGhHmMrKW0+xxrwsZMKXJhzdu39dmGA3aB4+b4n+HNask3KtCaVJue6yP6tTzf4WZvccyFJGLhAesNfJk2/X0NNHCzr7Z0p9pSHudHbx3sEEH0+M4fmRlrP03cCTykOaYSWPaZm2DtDmYUVQVJri0OGC1vVCyXqxsrzAgjk3nWUYRaYCyaIN187jYJpa2n3wORUXP+KVugwtm7iCdV795zjLII2zqj8S1uSvEWtiO1BBK1UgHUiIfbY7rB1F3rkUSKWH+fgzqInA/73Bsd/Tlk1Q4dxsYrmCNgXgtMJqJmuUJgDBu5AziTqW3lJfn/rHhYGNU5hgE5H8oGoQ7u6bd8/i9qc+CD+195cAbzOeNUfXMwGP8pUq1c3ckrzcEJOml7B2+tx90f3dFcyMbEWOREKHppL5CUjyktdWox2d4zNfGw/HsA5XMmmEwXdpYEzmUH2e3iKMJXO57vnZDUXDjw9nGZHANO5y6xB1JegFLJjXdJw3MlJ8u5brudf8ilEh0EEWaLetciE+S3N08WjqLrvErN7sOYOdHYjU3g3HP7TyWE7Gax4wxyyTHGgDC3VLaL74drgrTNQxl2pNjB8s0=
    userKey: AgConorp2gQZO1QHB4sXN/zNLClWiJCeoZj+3Ptzbd51ETfMQxiqIH8npQDZ+Lh8iWAzvgmgWxuPmNK9/oeW6tDUz4qMu4VVxdNRjkQ/upon/i9/gvEld284kfeV6jAxM6H8wy7GYu/To/kZCk+CDXmneX0aBRiP9PV0alENoBdIIdeOPIBgCEj7lP3FR2eBvYPXoMPk3BJ+bhXc6daxd6w9WQps+YA0kdBId5YFImMIcOiQ8TsO+ShS5bxvfXiasY54gVw7rO9zumj7+s+Ce/26d6us1Gs6N268esxZ/s5zC+OYl2s2SYyeusnYN1Y9DXOlmSP+Q+Cieif1KGA57m6tFLWeZRx4ICu1SUK5WdflywuN2T4cFRzJIv8AbVJIaoaUBMl4bPGhH2U0+a9IpY4KgoIAjRK3cwbxrl+dXs8cHWhF9ux+EIwYyeELyjSUwAqxgvpZG2OQJjmy2cZmB3mbbQiN66zPuTzaZksoAM/QB470bjwazG37b1G/9I5RoegEnGVk5YO6aFapxRfgnfY3RQRDs0GPo9HS6TrHqDyGzSDQvx6Psd+vChByPcHWik0oKIml9G3SOQ76iqG2ck2Lhf+iFZXWJQf4dcXg2YRvNSNaO+EWq6RYoxviWGI31O7REQliR+Cp+EUvcIB1lQUDsXglTO29Wo5lHBwgtwJqa8ldWsBvtJgu7a0Wc0jFZgGeEFTA5J03al4chCg0rQyjgquNYaFZvdmSXIe2Ze2njVOYCKsz3p80
  template:
    metadata:
      name: ceph-csi-rbd-secret
      namespace: ceph-csi-rbd
