resources:
  - https://raw.githubusercontent.com/bitnami-labs/sealed-secrets/v0.15.0/helm/sealed-secrets/crds/sealedsecret-crd.yaml
  - https://github.com/jetstack/cert-manager/releases/download/v1.2.0/cert-manager.crds.yaml
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v9.18.0/traefik/crds/ingressroute.yaml
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v9.18.0/traefik/crds/ingressroutetcp.yaml
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v9.18.0/traefik/crds/ingressrouteudp.yaml
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v9.18.0/traefik/crds/middlewares.yaml
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v9.18.0/traefik/crds/serverstransports.yaml
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v9.18.0/traefik/crds/tlsoptions.yaml
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v9.18.0/traefik/crds/tlsstores.yaml
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v9.18.0/traefik/crds/traefikservices.yaml
